blank_issues_enabled: false
contact_links:
  - name: Soporte general
    url: https://github.com/JavierDolo/PatientCareTrack/discussions
    about: Usa esta sección para preguntas o discusiones generales.
