---
name: "Task - Proyecto Residencia"
description: "Crea una tarea para el proyecto Residencia (Java + React)"
title: "[Task] "
labels:
  - task
assignees: []
body:
  - type: dropdown
    id: level
    attributes:
      label: Nivel
      description: Selecciona el nivel al que pertenece esta tarea
      options:
        - Nivel 1 (CRUD + JWT + Roles)
        - Nivel 2 (Logging + Caché)
        - Nivel 3 (Pruebas de integración)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Área
      description: Selecciona el área del proyecto
      options:
        - Backend (Java - Spring Boot)
        - Frontend (React.js)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      description: Define la prioridad de esta tarea
      options:
        - Alta
        - Media
        - Baja
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Explica brevemente la tarea a realizar
      placeholder: "Ejemplo: Implementar login con JWT en el backend"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos
      description: Lista de pasos sugeridos para esta tarea
      placeholder: |
        1. Crear endpoint en backend
        2. Configurar seguridad en Spring
        3. Probar con Postman
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Resultado esperado
      description: Explica el resultado que debe obtenerse si la tarea está bien implementada
      placeholder: "Ejemplo: Usuario puede iniciar sesión y obtener un JWT válido"
    validations:
      required: true
