name: Task: Proyecto Residencia
description: Crea una tarea para el proyecto Residencia (Java + React)
title: "[Task] "
labels: ["task"]
assignees: []
body:
  - type: dropdown
    id: level
    attributes:
      label: Nivel
      description: Selecciona el nivel al que pertenece esta tarea
      options:
        - Nivel 1 (CRUD + JWT + Roles)
        - Nivel 2 (Logging + Caché)
        - Nivel 3 (Pruebas de integración)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Área
      options:
        - Backend (Spring Boot)
        - Frontend (React)
        - Documentación
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridad
      options:
        - Alta
        - Media
        - Baja
      default: 1
    validations:
      required: true

  - type: input
    id: estimate
    attributes:
      label: Estimación
      placeholder: "Ej: 3h o 5 puntos"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Descripción
      description: Explica qué hay que hacer exactamente
      placeholder: "Detalles de la tarea..."
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: Subtareas (checklist)
      description: Una por línea; se convertirá en checklist
      value: |
        - [ ] Paso 1
        - [ ] Paso 2
        - [ ] Paso 3
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      description: ¿Cómo sabremos que está hecho?
      placeholder: |
        - El login devuelve JWT válido
        - Devuelve 401 si credenciales incorrectas
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Contexto adicional
      description: Links a PRs, diseños, decisiones, etc.
    validations:
      required: false

